asprs3/Controllers/SignUpController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using asprs3.Models;
using System.Web.WebPages;
using asprs3.Models;


namespace asprs3.Controllers
{
    public class SignUpController : Controller
    {

        Model1 db = new Model1();
        public SignUpController()
        {
            db = new Model1();
        }

        public ActionResult SelectStudent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ViewStudent(Student viewModel)
        //Get entered Student information and query it against Students, if student exists in Students, add Guardianship entity
        {
            var FName = viewModel.StudentFName;
            var LName = viewModel.StudentLName;
            var DOB = viewModel.StudentDOB;

            var existingStudent = from m in db.Students
                                  where
                                    m.StudentFName == FName 
                                    && m.StudentLName == LName 
                                    && DOB.Equals(m.StudentDOB)
                                  select m;

            return View(existingStudent.ToList());
        }


    }
}

asprs3/Views/SignUp/SelectStudent.cshtml
@model asprs3.Models.Student
@{
    ViewBag.Title = "SelectStudent";
}
<p>
    @Html.ActionLink("Back", "Index", "Home")
</p>
@using (Html.BeginForm("ViewStudent", "SignUp", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.StudentFName)
        @Html.TextBoxFor(m => m.StudentFName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.StudentFName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StudentLName)
        @Html.TextBoxFor(m => m.StudentLName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.StudentLName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StudentDOB)
        @Html.EditorFor(m => m.StudentDOB, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(m => m.StudentDOB)
    </div>
    <button type="submit" value="Find Student" class="btn btn-primary">Find Student</button>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

asprs3/Views/SignUp/ViewStudent.cshtml
@model IEnumerable<asprs3.Models.Student>

@{
    ViewBag.Title = "ViewStudent";
}

<h2>View Student</h2>

<p>
    @Html.ActionLink("Back", "SelectStudent", "SignUp")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentFName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentLName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentDOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentGrade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StudentFName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StudentLName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StudentDOB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StudentGrade)
        </td>
        <td>
            @Html.ActionLink("Register", "ViewActivities", new { id = item.StudentID }) |

        </td>
    </tr>
}

</table>

<hr />
<button type="submit" value="Register Student" class="btn btn-primary">Register Student</button>